<a href="https://colab.research.google.com/github/uzmakhan7/uk/blob/master/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf
import pandas as pd

In [0]:
dir(tensorflow)

['AUTO_REUSE',
 'AggregationMethod',
 'Assert',
 'AttrValue',
 'COMPILER_VERSION',
 'CXX11_ABI_FLAG',
 'ConditionalAccumulator',
 'ConditionalAccumulatorBase',
 'ConfigProto',
 'CriticalSection',
 'DType',
 'DeviceSpec',
 'Dimension',
 'Event',
 'FIFOQueue',
 'FixedLenFeature',
 'FixedLenSequenceFeature',
 'FixedLengthRecordReader',
 'GIT_VERSION',
 'GPUOptions',
 'GRAPH_DEF_VERSION',
 'GRAPH_DEF_VERSION_MIN_CONSUMER',
 'GRAPH_DEF_VERSION_MIN_PRODUCER',
 'GradientTape',
 'Graph',
 'GraphDef',
 'GraphKeys',
 'GraphOptions',
 'HistogramProto',
 'IdentityReader',
 'IndexedSlices',
 'InteractiveSession',
 'LMDBReader',
 'LogMessage',
 'MONOLITHIC_BUILD',
 'MetaGraphDef',
 'Module',
 'NameAttrList',
 'NoGradient',
 'NodeDef',
 'NotDifferentiable',
 'OpError',
 'Operation',
 'OptimizerOptions',
 'PaddingFIFOQueue',
 'Print',
 'PriorityQueue',
 'QUANTIZED_DTYPES',
 'QueueBase',
 'RaggedTensor',
 'RandomShuffleQueue',
 'ReaderBase',
 'RegisterGradient',
 'RunMetadata',
 'RunOptions',
 'Session

In [0]:
!pip3 list | grep -i tensorflow

mesh-tensorflow          0.0.5                
tensorflow               1.14.0               
tensorflow-estimator     1.14.0               
tensorflow-hub           0.4.0                
tensorflow-metadata      0.13.0               
tensorflow-probability   0.7.0                


In [0]:
#to assign fix value in tensorflow,we need to define constant
x=tf.constant([30])

In [0]:
x1=tf.constant([3,5,66,88])  #multi value constant

In [0]:
type(x)

tensorflow.python.framework.ops.Tensor

In [0]:
y=tf.constant(20)

In [0]:
z=x+y

In [0]:
z1=tf.add(x,y)

In [0]:
#now time for assigning resources to our equation
sess=tf.Session() #connect cpu,gpu tpu

In [0]:
#now we can run our equatin
output=sess.run(z)

In [0]:
output

array([50], dtype=int32)

In [0]:
sess.close()   #closing session

In [0]:
#we can perform same task in another way
with tf.Session() as sess:
  output1=sess.run(z)
  tf.summary.FileWriter(output1)

In [0]:
output1

array([50], dtype=int32)

placeholder

In [0]:
#first placeholder
p1=tf.placeholder(tf.int32)

In [0]:
#placeholder2
p2=tf.placeholder(tf.int32)

In [0]:
sum=tf.add(p1,p2)  #adding values

In [0]:
#general
sum1=p1+p2

In [0]:
#time for creating session
with tf.Session() as sess:
  output2=sess.run(sum1,{p1:[3,6],p2:[5,8]})

In [0]:
output2

array([ 8, 14], dtype=int32)